/* tslint:disable */
/* eslint-disable */
/**
 * Equipment Registry Api
 * Equipment Registry management for hospital system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';

/**
 * 
 * @export
 * @interface EquipmentStatusUpdate
 */
export interface EquipmentStatusUpdate {
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof EquipmentStatusUpdate
     */
    status: EquipmentStatus;
}

/**
 * Check if a given object implements the EquipmentStatusUpdate interface.
 */
export function instanceOfEquipmentStatusUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function EquipmentStatusUpdateFromJSON(json: any): EquipmentStatusUpdate {
    return EquipmentStatusUpdateFromJSONTyped(json, false);
}

export function EquipmentStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentStatusUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': EquipmentStatusFromJSON(json['status']),
    };
}

export function EquipmentStatusUpdateToJSON(value?: EquipmentStatusUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': EquipmentStatusToJSON(value.status),
    };
}

