/* tslint:disable */
/* eslint-disable */
/**
 * Equipment Registry Api
 * Equipment Registry management for hospital system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * 
 * @export
 * @interface Equipment
 */
export interface Equipment {
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    category: EquipmentCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    manufacturer: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    serialNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof Equipment
     */
    purchaseDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Equipment
     */
    warrantyUntil?: Date;
    /**
     * 
     * @type {number}
     * @memberof Equipment
     */
    lifespanYears?: number;
    /**
     * 
     * @type {number}
     * @memberof Equipment
     */
    purchasePrice?: number;
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof Equipment
     */
    status: EquipmentStatus;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    note?: string;
    /**
     * 
     * @type {Location}
     * @memberof Equipment
     */
    location: Location;
}


/**
 * @export
 */
export const EquipmentCategoryEnum = {
    Imaging: 'imaging',
    Monitoring: 'monitoring',
    Infusion: 'infusion',
    Surgical: 'surgical',
    Emergency: 'emergency'
} as const;
export type EquipmentCategoryEnum = typeof EquipmentCategoryEnum[keyof typeof EquipmentCategoryEnum];


/**
 * Check if a given object implements the Equipment interface.
 */
export function instanceOfEquipment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "manufacturer" in value;
    isInstance = isInstance && "serialNumber" in value;
    isInstance = isInstance && "purchaseDate" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function EquipmentFromJSON(json: any): Equipment {
    return EquipmentFromJSONTyped(json, false);
}

export function EquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Equipment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'category': json['category'],
        'manufacturer': json['manufacturer'],
        'serialNumber': json['serialNumber'],
        'purchaseDate': (new Date(json['purchaseDate'])),
        'warrantyUntil': !exists(json, 'warrantyUntil') ? undefined : (new Date(json['warrantyUntil'])),
        'lifespanYears': !exists(json, 'lifespanYears') ? undefined : json['lifespanYears'],
        'purchasePrice': !exists(json, 'purchasePrice') ? undefined : json['purchasePrice'],
        'status': EquipmentStatusFromJSON(json['status']),
        'note': !exists(json, 'note') ? undefined : json['note'],
        'location': LocationFromJSON(json['location']),
    };
}

export function EquipmentToJSON(value?: Equipment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'category': value.category,
        'manufacturer': value.manufacturer,
        'serialNumber': value.serialNumber,
        'purchaseDate': (value.purchaseDate.toISOString().substr(0,10)),
        'warrantyUntil': value.warrantyUntil === undefined ? undefined : (value.warrantyUntil.toISOString().substr(0,10)),
        'lifespanYears': value.lifespanYears,
        'purchasePrice': value.purchasePrice,
        'status': EquipmentStatusToJSON(value.status),
        'note': value.note,
        'location': LocationToJSON(value.location),
    };
}

