/* tslint:disable */
/* eslint-disable */
/**
 * Equipment Registry Api
 * Equipment Registry management for hospital system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Equipment,
  EquipmentStatusUpdate,
} from '../models';
import {
    EquipmentFromJSON,
    EquipmentToJSON,
    EquipmentStatusUpdateFromJSON,
    EquipmentStatusUpdateToJSON,
} from '../models';

export interface CreateEquipmentRequest {
    equipment: Equipment;
}

export interface DeleteEquipmentRequest {
    equipmentId: string;
}

export interface GetEquipmentRequest {
    equipmentId: string;
}

export interface ListEquipmentRequest {
    status?: ListEquipmentStatusEnum;
    department?: string;
    category?: string;
}

export interface UpdateEquipmentRequest {
    equipmentId: string;
    equipment: Equipment;
}

export interface UpdateEquipmentStatusRequest {
    equipmentId: string;
    equipmentStatusUpdate: EquipmentStatusUpdate;
}

/**
 * EquipmentRegistryApi - interface
 * 
 * @export
 * @interface EquipmentRegistryApiInterface
 */
export interface EquipmentRegistryApiInterface {
    /**
     * 
     * @summary Creates new equipment entry
     * @param {Equipment} equipment 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    createEquipmentRaw(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Creates new equipment entry
     */
    createEquipment(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

    /**
     * 
     * @summary Permanently deletes equipment record
     * @param {string} equipmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    deleteEquipmentRaw(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently deletes equipment record
     */
    deleteEquipment(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Returns details of equipment
     * @param {string} equipmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    getEquipmentRaw(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Returns details of equipment
     */
    getEquipment(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

    /**
     * 
     * @summary Returns list of all equipment
     * @param {'active' | 'damaged' | 'decommissioned'} [status] 
     * @param {string} [department] 
     * @param {string} [category] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    listEquipmentRaw(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Equipment>>>;

    /**
     * Returns list of all equipment
     */
    listEquipment(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Equipment>>;

    /**
     * 
     * @summary Updates equipment entry
     * @param {string} equipmentId 
     * @param {Equipment} equipment 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    updateEquipmentRaw(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Updates equipment entry
     */
    updateEquipment(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

    /**
     * 
     * @summary Updates equipment status (e.g. decommission)
     * @param {string} equipmentId 
     * @param {EquipmentStatusUpdate} equipmentStatusUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentRegistryApiInterface
     */
    updateEquipmentStatusRaw(requestParameters: UpdateEquipmentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Updates equipment status (e.g. decommission)
     */
    updateEquipmentStatus(requestParameters: UpdateEquipmentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

}

/**
 * 
 */
export class EquipmentRegistryApi extends runtime.BaseAPI implements EquipmentRegistryApiInterface {

    /**
     * Creates new equipment entry
     */
    async createEquipmentRaw(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipment === null || requestParameters.equipment === undefined) {
            throw new runtime.RequiredError('equipment','Required parameter requestParameters.equipment was null or undefined when calling createEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/equipment`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentToJSON(requestParameters.equipment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Creates new equipment entry
     */
    async createEquipment(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.createEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes equipment record
     */
    async deleteEquipmentRaw(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling deleteEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes equipment record
     */
    async deleteEquipment(requestParameters: DeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEquipmentRaw(requestParameters, initOverrides);
    }

    /**
     * Returns details of equipment
     */
    async getEquipmentRaw(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling getEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Returns details of equipment
     */
    async getEquipment(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.getEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns list of all equipment
     */
    async listEquipmentRaw(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Equipment>>> {
        const queryParameters: any = {};

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.department !== undefined) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.category !== undefined) {
            queryParameters['category'] = requestParameters.category;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EquipmentFromJSON));
    }

    /**
     * Returns list of all equipment
     */
    async listEquipment(requestParameters: ListEquipmentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Equipment>> {
        const response = await this.listEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates equipment entry
     */
    async updateEquipmentRaw(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling updateEquipment.');
        }

        if (requestParameters.equipment === null || requestParameters.equipment === undefined) {
            throw new runtime.RequiredError('equipment','Required parameter requestParameters.equipment was null or undefined when calling updateEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentToJSON(requestParameters.equipment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Updates equipment entry
     */
    async updateEquipment(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.updateEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates equipment status (e.g. decommission)
     */
    async updateEquipmentStatusRaw(requestParameters: UpdateEquipmentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling updateEquipmentStatus.');
        }

        if (requestParameters.equipmentStatusUpdate === null || requestParameters.equipmentStatusUpdate === undefined) {
            throw new runtime.RequiredError('equipmentStatusUpdate','Required parameter requestParameters.equipmentStatusUpdate was null or undefined when calling updateEquipmentStatus.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentStatusUpdateToJSON(requestParameters.equipmentStatusUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Updates equipment status (e.g. decommission)
     */
    async updateEquipmentStatus(requestParameters: UpdateEquipmentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.updateEquipmentStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEquipmentStatusEnum = {
    Active: 'active',
    Damaged: 'damaged',
    Decommissioned: 'decommissioned'
} as const;
export type ListEquipmentStatusEnum = typeof ListEquipmentStatusEnum[keyof typeof ListEquipmentStatusEnum];
