/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XleEquipmentList {
    }
}
export interface XleEquipmentListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXleEquipmentListElement;
}
declare global {
    interface HTMLXleEquipmentListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXleEquipmentListElement extends Components.XleEquipmentList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXleEquipmentListElementEventMap>(type: K, listener: (this: HTMLXleEquipmentListElement, ev: XleEquipmentListCustomEvent<HTMLXleEquipmentListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXleEquipmentListElementEventMap>(type: K, listener: (this: HTMLXleEquipmentListElement, ev: XleEquipmentListCustomEvent<HTMLXleEquipmentListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXleEquipmentListElement: {
        prototype: HTMLXleEquipmentListElement;
        new (): HTMLXleEquipmentListElement;
    };
    interface HTMLElementTagNameMap {
        "xle-equipment-list": HTMLXleEquipmentListElement;
    }
}
declare namespace LocalJSX {
    interface XleEquipmentList {
        "onEntry-clicked"?: (event: XleEquipmentListCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "xle-equipment-list": XleEquipmentList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xle-equipment-list": LocalJSX.IntrinsicElements["xle-equipment-list"] & JSXBase.HTMLAttributes<HTMLXleEquipmentListElement>;
        }
    }
}
